dataset: 'cifar100'
backbone: 'resnet32'
classifier: 'dot_product_classifier'
imb_type: 'exp'
imb_factor: 0.01
loss_type: 'CE'
train_rule: 'None'
start_epoch: 0
epochs: 300
batch_size: 128
optimizer: 'sgd'
learning_rate: 0.1
momentum: 0.9
weight_decay: 2e-4
print_freq: 10
workers: 4
rand_number: 0
gpu: 0
root_log: 'log_cifar100'
root_model: 'checkpoint_cifar100'
mixup_alpha: 1.
mixup_type: 'mixup'
k_majority: 3
tau: 0.5
mamix_ratio: -0.25
