language: python
python:
  - "3.6"
notifications:
  email: true
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python -m unittest -v
after success:
  - python -m pylint deepimblearn
